### ISSUE TITLE
Roadmap towards formally verifying LLBC and LLBC#

### ISSUE THREAD

**Issue by Cemoixerestre** [AeneasVerif/mechanized-llbc#1]
- Simulations proved:
  - [ ] Stability of HLPL
  - [x] Preservation of $$\leq$$ by HLPL+
  - [ ] Simulation between LLBC and HLPL+
  - [ ] Stability of LLBC
  - [x] Preservation of $$\leq$$ by LLBC+
  - [x] Simulation between LLBC# and LLBC+
 
- Language features:
  - [x] Mutable references
  - [ ] Shared references
  - [x] Conditional structures
  - [x] Loops
  - [ ] Function calls/returns
